version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: docker
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /backend
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /pipelines
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: /frontend
  schedule:
    interval: yearly
  ignore:
    # For all deps
    - dependency-name: "*"
      # ignore all major updates
      update-types: ["version-update:semver-major"]
