services:
  db:
    image: kartoza/postgis:16-3.4
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql

  memcached:
    extends:
      file: compose.base.yaml
      service: memcached

  worldguess-frontend:
    extends:
      file: compose.base.yaml
      service: worldguess-frontend
    restart: no

  worldguess-pipelines:
    extends:
      file: compose.base.yaml
      service: worldguess-pipelines
    depends_on:
      - db
      - memcached
    restart: no

  worldguess-backend:
    extends:
      file: compose.base.yaml
      service: worldguess-backend
    depends_on:
      - worldguess-frontend
      - db
      - memcached
