services:
  db:
    image: kartoza/postgis:16-3.4
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql

  worldguess-frontend:
    image: worldguess-frontend:latest
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: cp -r /frontend/build/ /static
    volumes:
      - ${STATIC_DIR_PATH}:/static

  worldguess-pipelines:
    image: worldguess-pipelines
    pull_policy: never
    build:
      context: ./pipelines
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db

  worldguess-backend:
    image: worldguess-backend:latest
    pull_policy: never
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - worldguess-frontend
      - db
    volumes:
      - ${STATIC_DIR_PATH}:/static
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      STATIC_DIR: /static/build
      PORT: 8000
