services:
  memcached:
    image: memcached:1.6.31

  worldguess-frontend:
    image: worldguess-frontend:latest
    pull_policy: never
    restart: no
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: cp -r /frontend/build/ /static
    volumes:
      - ${STATIC_DIR_PATH}:/static

  worldguess-pipelines:
    image: worldguess-pipelines
    pull_policy: never
    restart: no
    build:
      context: ./
      dockerfile: ./pipelines/Dockerfile
    volumes:
      - ${WORLDPOP_CACHE_PATH}:/tmp/worldguess_cache
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      MEMCACHE_SERVER: memcached

  worldguess-backend:
    image: worldguess-backend:latest
    pull_policy: never
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ${STATIC_DIR_PATH}:/static
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MEMCACHE_SERVER: memcached
      STATIC_DIR: /static/build
      PORT: 8000
      BASE_URL: ${BASE_URL}
