services:
  db:
    image: kartoza/postgis:16-3.4
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DB_PATH}:/var/lib/postgresql

  worldguess-frontend:
    extends:
      file: compose.base.yaml
      service: worldguess-frontend

  worldguess-pipelines:
    extends:
      file: compose.base.yaml
      service: worldguess-pipelines

  worldguess-backend:
    extends:
      file: compose.base.yaml
      service: worldguess-backend
