[tool.poetry]
name = "worldguess"
version = "0.1.0"
description = ""
authors = ["Matheus Fillipe <matheusfillipeag@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
sqlalchemy = "^2.0.36"
uvicorn = "^0.31.0"
pydantic-settings = "^2.5.2"
pydantic-geojson = "^0.1.1"
geoalchemy2 = "^0.15.2"
pymemcache = "^4.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
ruff = "^0.6.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.docformatter]
wrap-summaries = 120
wrap-descriptions = 120
in-place = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
line-length = 120
