[tool.poetry]
name = "worldguess"
version = "0.1.0"
description = ""
authors = ["Matheus Fillipe <matheusfillipeag@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.114.2"
sqlalchemy = "^2.0.34"
uvicorn = "^0.30.6"
pydantic-settings = "^2.5.2"
pydantic-geojson = "^0.1.1"
geoalchemy2 = "^0.15.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
ruff = "^0.6.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
