files: ^pipelines/
exclude: ^pipelines/backend/
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix", "--output-format=github"]
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [ "--fix", "--output-format=github" ]

  - repo: https://github.com/myint/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
    - id: docformatter
      args: ["--config", "./pyproject.toml", "-i"]
      additional_dependencies: ['.[tomli]']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports, --disable-error-code, misc]
      additional_dependencies: [types-requests]
