name: Backend checks

on:
  push:
    paths:
    - 'backend/**'
    - './github/workflows/backend.yaml'

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Run pre commit checks
      - run: python -m pip install pre-commit
        shell: bash
      - run: python -m pip freeze --local
        shell: bash
      - run: pre-commit run --show-diff-on-failure --color=always
        id: pre-commit-check
        name: Pre Commit Checks
        shell: bash
