name: Build and Deploy Worldguess

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: h4ks-com/k3s-deploy/.github/workflows/k3s-deploy.yaml@main
    with:
      contexts: "./frontend,./backend"
      images: "worldguess-frontend,worldguess-backend"
