name: Build and Deploy Worldguess

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: h4ks-com/k3s-deploy/.github/workflows/k3s-deploy.yaml@main
    with:
      namespace: worldguess
      deployment-name: worldguess-backend
      services: |
        [
          {
            "context": "./frontend",
            "image": "worldguess-frontend",
            "containers": ["frontend-builder"]
          },
          {
            "context": ".",
            "dockerfile": "./pipelines/Dockerfile",
            "image": "worldguess-pipelines",
            "containers": []
          },
          {
            "context": "./backend",
            "image": "worldguess-backend",
            "containers": ["backend"]
          }
        ]
      job-config: |
        {
          "name": "worldguess-pipelines",
          "template": "worldguess-pipelines"
        }
