name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/docker-backend.yml'
      - '.github/workflows/docker-build-push.yml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: worldguess-backend
      context: ./backend
      dockerfile: ./backend/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
