name: Pipeline Checks

on:
  push:
    paths:
    - 'pipelines/**'
    - 'github/workflows/pipelines.yaml'

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipelines
        shell: bash
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Run pre commit checks
      - run: python -m pip install pre-commit==3.8.0
      - run: python -m pip freeze --local
      - run: pre-commit run --all --show-diff-on-failure --color=always
        name: Pre Commit Checks
